Added class to perform univariate filtering based on inter quantile range
ww-tech/primrose pull request #97
Opened 2021-01-05 15:18 UTC by astro313

## Description
New feature in preprocessing data -- performing filtering on a list of columns based on their interquartile range. 

## Checklist

- [x] I squashed my commits to a reasonable number of descriptive commits.
- [x] I ran the tests, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

2021-01-13 15:46 UTC, reka-ww commented on primrose/transformers/filter.py
> +        pass
How do you make sure that we don't consider the testing data to determine IQR?

2021-01-13 16:00 UTC, astro313 commented on primrose/transformers/filter.py
> +        pass
@reka-ww  I'll fix that today.

2021-01-13 16:04 UTC, briangrahamww commented on primrose/transformers/filter.py
>      Michael Skarlinski (michael.skarlinski@weightwatchers.com)
@astro313 , you can add yourself to this list 😄

2021-01-13 16:51 UTC, briangrahamww commented on primrose/transformers/filter.py
> +        df = df.dropna(inplace=False)
I think we have other transformers that have options for dealing with nans. We might want to keep this to the single use case of just filtering out outliers based on IQR.  That way it's explicitly declared with the rest of the data transformations if you are dropping nans and at what point in the pipeline.

2021-01-13 16:54 UTC, briangrahamww requested changes
I think it's best to separate the nan removal.

2021-03-11 20:40 UTC, kzecchini commented
@astro313 @briangrahamww curious about the progress on this

2021-03-11 21:28 UTC, astro313 commented
After discussing with @reka-ww , we want to think more about how to implement this/should we implement this. Will close this PR for now.

2021-03-11 21:28 UTC, closed without merging